[package]
name = "petal-clustering"
version = "0.1.0"
authors = ["Min Shao <min.shao1988@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "0.12"
petal-neighbors = {git = "https://github.com/petabi/petal-neighbors.git", rev = "d514910d"}

[dev-dependencies]
rusty-machine = "0.5"
